### ISSUE TITLE
File requirements.txt Jinja version mismatch

### ISSUE THREAD

**Issue by adamvm** [nlohmann/mutate_cpp#20]
Hi,

during installation of packages in venv from requirements.txt I received this:

**Successfully built Flask-Compress Flask-Humanize humanize itsdangerous MarkupSafe psutil SQLAlchemy sqlalchemy-migrate Tempita WTForms
ERROR: flask 1.0 has requirement Jinja2>=2.10, but you'll have jinja2 2.9.6 which is incompatible.**

**Comment by nlohmann** [comment]
See https://github.com/nlohmann/mutate_cpp/commit/96b6ca51ce19d0ffc064f3dd2274fabb8a13c59d.
